{
  try {
    template.sendBody("direct:fail","Hello World");
    fail("Should have thrown an exception");
  }
 catch (  Exception e) {
    assertIsInstanceOf(IllegalArgumentException.class,e.getCause());
  }
  context.stop();
}
