{
  try {
    AssertUtils.notNull(null,"message");
    Assert.fail("Should have thrown exception");
  }
 catch (  IllegalArgumentException e) {
    Assert.assertEquals("[Assert not null] message",e.getMessage());
  }
}
