{
  if (catchClauses == null) {
    return;
  }
  for (  CatchProcessor catchClause : catchClauses) {
    Throwable caught=catchClause.catches(exchange,e);
    if (caught != null) {
      if (LOG.isTraceEnabled()) {
        LOG.trace("This TryProcessor catches the exception: " + caught.getClass().getName() + " caused by: "+ e.getMessage());
      }
      exchange.setProperty(Exchange.EXCEPTION_CAUGHT,caught);
      exchange.setException(null);
      catchClause.process(exchange);
      boolean handled=catchClause.handles(exchange);
      if (LOG.isDebugEnabled()) {
        LOG.debug("The exception is handled: " + handled + " for the exception: "+ e.getClass().getName()+ " caused by: "+ caught.getMessage());
      }
      if (!handled) {
        if (exchange.getException() == null) {
          exchange.setException(exchange.getProperty(Exchange.EXCEPTION_CAUGHT,Exception.class));
        }
      }
      return;
    }
  }
  if (LOG.isTraceEnabled()) {
    LOG.trace("This TryProcessor does not catch the exception: " + e.getClass().getName() + " caused by: "+ e.getMessage());
  }
}
