{
  log.info("Received hang up - stopping the main instance.");
  try {
    MainSupport.this.stop();
  }
 catch (  Exception ex) {
    log.warn("Error during stopping the main instance.",ex);
  }
}
