{
  for (  CatchProcessor catchClause : catchClauses) {
    if (catchClause.catches(e)) {
      exchange.setException(e);
      try {
        catchClause.process(exchange);
      }
 catch (      Exception e1) {
        log.warn("Caught exception inside catch clause: " + e1,e1);
        throw e1;
      }
      return;
    }
  }
  throw e;
}
