{
  checkThrownException(mock,cl,null,expectedCauseClass);
}
