{
  try {
    GroovyLanguage.groovy("exchange.doesNotExist").evaluate(exchange);
    fail("This test case should have thrown an exception!");
  }
 catch (  Exception e) {
    LOG.debug("Caught expected exception: " + e,e);
    String message=e.getMessage();
    assertTrue("The message should include 'doesNotExist' but was: " + message,message.contains("doesNotExist"));
  }
}
