{
  try {
    faultProcessor.process(exchange);
  }
 catch (  Exception e) {
    exchange.setException(e);
  }
}
